version: '3'

volumes:
  db-data:

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/learning-management'
    environment:
      - 'DATABASE_PASSWORD=postgres'
      - 'WEBPACKER_DEV_SERVER_HOST=webpacker'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
      

  db:
    image: postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - '5432:5432'
  
  webpacker:
    build: .
    volumes:
      - '.:/learning-management'
    command: ./bin/webpack-dev-server
    environment:
      - 'NODE_ENV=development'
      - 'RAILS_ENV=development'
      - 'WEBPACKER_DEV_SERVER_HOST="0.0.0.0"'
    ports:
      - "3035:3035"
