FROM ruby:3.0.0
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client 
########################################################################
# yarnパッケージ管理ツールをインストール
RUN apt-get update && apt-get install -y curl apt-transport-https wget && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn
# Node.jsをインストール
RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install -y nodejs
########################################################################
WORKDIR /learning-management
COPY Gemfile Gemfile.lock /learning-management/
RUN bundle install
RUN yarn install --check-files

RUN bundle exec rails webpacker:compile
