FROM ruby:3.1.0
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    postgresql-client 
########################################################################
# yarnパッケージ管理ツールをインストール
RUN apt-get update && apt-get install -y curl apt-transport-https wget && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    apt-get update && apt-get install -y yarn
# Node.jsをインストール
RUN RUN curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && apt-get install -y nodejs
########################################################################
WORKDIR /product-register
COPY Gemfile Gemfile.lock /product-register
RUN bundle install
